sonar.organization=REEMPLAZAR_ORGANIZATION_KEY
sonar.projectKey=REEMPLAZAR_PROJECT_KEY
sonar.projectName=REEMPLAZAR_PROJECT_NAME

sonar.sourceEncoding=UTF-8
sonar.scm.provider=git

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=backend/src/test/java/**,frontend/src/**/*.spec.ts

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,frontend/coverage/**/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/cypress/**,**/*.cy.ts
